### ISSUE TITLE
How to build with newer boost/beast release?

### ISSUE THREAD

**Issue by Danp2** [pdckxd/WebSocketAsioAHK#1]
Can you provide some guidance on how to build an updated DLL using a more recent version of Boost/Beast? I'm using VSCode with gcc. I've downloaded the source and successfully build the `b2` executable, but I'm lost when it comes to integrating the boost library. 

Any help would be appreciated!

**Comment by Danp2** [comment]
FWIW, I was able to figure this out myself, and I'm able to build at least the 32 bit DLL so far. Seeing asserts coming from Boost that appear to be concurrency issues. See [here](https://stackoverflow.com/questions/52236810/boost-beast-async-server-failing-with-assertion-failed-id-tid-on-multip) for prior SO discussion.  I removed the `async_read` from `on_write` and that seems to have helped.

**Comment by Danp2** [comment]
Implemented a write queue and show [here](https://github.com/vinniefalco/CppCon2018/blob/8fc8528571561d2acee5c05f4b7a51861d1d496d/websocket_session.cpp#L87) and this appears to have resolved the concurrency issues and the calling routine no longer hangs on exit.

**Comment by pdckxd** [comment]
Good to hear. Thanks to let me know.
